repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: traefik
    url: https://traefik.github.io/charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: "39.0.0"
    values:
      - ingressRoute:
          dashboard:
            enabled: true
        ports:
          traefik:
            expose:
              default: true
        metrics:
          prometheus:
            serviceMonitor:
              enabled: true

  - name: prometheus
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: "81.5.0"
    values:
      - prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
        grafana:
          adminPassword: admin
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki-gateway.logging.svc.cluster.local
              access: proxy
              isDefault: false

  - name: loki
    namespace: logging
    createNamespace: true
    chart: grafana/loki
    values:
      - deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          useTestSchema: true
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        singleBinary:
          replicas: 1
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0

  - name: alloy
    namespace: logging
    chart: grafana/alloy
    needs:
      - logging/loki
    values:
      - alloy:
          configMap:
            content: |
              discovery.kubernetes "pods" {
                role = "pod"
              }
              discovery.relabel "pods" {
                targets = discovery.kubernetes.pods.targets
                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  target_label  = "namespace"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_name"]
                  target_label  = "pod"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_container_name"]
                  target_label  = "container"
                }
                rule {
                  source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_name", "__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
                  separator     = "/"
                  regex         = "(.+)/(.+)/(.+)/(.+)"
                  replacement   = "/var/log/pods/${1}_${2}_${3}/${4}/*.log"
                  target_label  = "__path__"
                }
              }
              local.file_match "pods" {
                path_targets = discovery.relabel.pods.output
              }
              loki.source.file "pods" {
                targets    = local.file_match.pods.targets
                forward_to = [loki.process.pods.receiver]
              }
              loki.process "pods" {
                stage.cri {}
                forward_to = [loki.write.default.receiver]
              }
              loki.write "default" {
                endpoint {
                  url = "http://loki-gateway/loki/api/v1/push"
                }
              }
          mounts:
            varlog: true
            dockercontainers: true

  - name: demo
    namespace: demo
    createNamespace: true
    chart: ./charts/demo-app
    needs:
      - traefik/traefik
      - monitoring/prometheus
    values:
      - image:
          repository: kube-demo
          tag: latest
          pullPolicy: IfNotPresent

        redis:
          enabled: true
          auth:
            password: demo-password

        secrets:
          redisPassword: demo-password
          apiKey: meetup-demo-key

        config:
          logLevel: INFO
          queueName: task_queue
          maxRetries: "3"

        api:
          replicas: 2
        worker:
          replicas: 2

        ingress:
          enabled: true
          pathPrefix: /api

        serviceMonitor:
          enabled: true
